import { Food } from "@/types";

export const COMMON_FOODS: Food[] = [
  { id: "chicken-breast",   name: "Chicken Breast",      calories: 165, protein: 31,  carbs: 0,    fat: 3.6, servingSize: "100g" },
  { id: "brown-rice",       name: "Brown Rice",          calories: 216, protein: 5,   carbs: 45,   fat: 1.8, servingSize: "1 cup cooked" },
  { id: "eggs",             name: "Eggs",                calories: 78,  protein: 6,   carbs: 0.6,  fat: 5,   servingSize: "1 large" },
  { id: "banana",           name: "Banana",              calories: 105, protein: 1.3, carbs: 27,   fat: 0.4, servingSize: "1 medium" },
  { id: "apple",            name: "Apple",               calories: 95,  protein: 0.5, carbs: 25,   fat: 0.3, servingSize: "1 medium" },
  { id: "oatmeal",          name: "Oatmeal",             calories: 166, protein: 5.9, carbs: 28,   fat: 3.6, servingSize: "1 cup cooked" },
  { id: "salmon",           name: "Salmon",              calories: 208, protein: 20,  carbs: 0,    fat: 13,  servingSize: "100g" },
  { id: "broccoli",         name: "Broccoli",            calories: 55,  protein: 3.7, carbs: 11,   fat: 0.6, servingSize: "1 cup" },
  { id: "sweet-potato",     name: "Sweet Potato",        calories: 103, protein: 2.3, carbs: 24,   fat: 0.1, servingSize: "1 medium" },
  { id: "greek-yogurt",     name: "Greek Yogurt",        calories: 130, protein: 22,  carbs: 9,    fat: 0,   servingSize: "1 cup" },
  { id: "almonds",          name: "Almonds",             calories: 164, protein: 6,   carbs: 6,    fat: 14,  servingSize: "1 oz" },
  { id: "whole-milk",       name: "Whole Milk",          calories: 149, protein: 8,   carbs: 12,   fat: 8,   servingSize: "1 cup" },
  { id: "cheddar-cheese",   name: "Cheddar Cheese",      calories: 113, protein: 7,   carbs: 0.4,  fat: 9,   servingSize: "1 oz" },
  { id: "white-rice",       name: "White Rice",          calories: 242, protein: 4.4, carbs: 53,   fat: 0.4, servingSize: "1 cup cooked" },
  { id: "pasta",            name: "Pasta",               calories: 220, protein: 8,   carbs: 43,   fat: 1.3, servingSize: "1 cup cooked" },
  { id: "wheat-bread",      name: "Whole Wheat Bread",   calories: 81,  protein: 4,   carbs: 15,   fat: 1.1, servingSize: "1 slice" },
  { id: "orange",           name: "Orange",              calories: 62,  protein: 1.2, carbs: 15,   fat: 0.2, servingSize: "1 medium" },
  { id: "strawberries",     name: "Strawberries",        calories: 49,  protein: 1,   carbs: 12,   fat: 0.5, servingSize: "1 cup" },
  { id: "avocado",          name: "Avocado",             calories: 234, protein: 2.9, carbs: 12,   fat: 21,  servingSize: "1 medium" },
  { id: "canned-tuna",      name: "Canned Tuna",         calories: 116, protein: 26,  carbs: 0,    fat: 1,   servingSize: "100g" },
  { id: "ground-beef",      name: "Ground Beef 80/20",   calories: 254, protein: 17,  carbs: 0,    fat: 20,  servingSize: "100g" },
  { id: "black-beans",      name: "Black Beans",         calories: 227, protein: 15,  carbs: 41,   fat: 0.9, servingSize: "1 cup cooked" },
  { id: "lentils",          name: "Lentils",             calories: 230, protein: 18,  carbs: 40,   fat: 0.8, servingSize: "1 cup cooked" },
  { id: "cottage-cheese",   name: "Cottage Cheese",      calories: 206, protein: 28,  carbs: 8,    fat: 4.5, servingSize: "1 cup" },
  { id: "spinach",          name: "Spinach",             calories: 7,   protein: 0.9, carbs: 1.1,  fat: 0.1, servingSize: "1 cup raw" },
];
